INSERT INTO genres(id, name) VALUES ('2', 'Point-and-click');
INSERT INTO genres(id, name) VALUES ('4', 'Fighting');
INSERT INTO genres(id, name) VALUES ('5', 'Shooter');
INSERT INTO genres(id, name) VALUES ('7', 'Music');
INSERT INTO genres(id, name) VALUES ('8', 'Platform');
INSERT INTO genres(id, name) VALUES ('9', 'Puzzle');
INSERT INTO genres(id, name) VALUES ('10', 'Racing');
INSERT INTO genres(id, name) VALUES ('11', 'Real Time Strategy (RTS)');
INSERT INTO genres(id, name) VALUES ('12', 'Role-playing (RPG)');
INSERT INTO genres(id, name) VALUES ('13', 'Simulator');
INSERT INTO genres(id, name) VALUES ('14', 'Sport');
INSERT INTO genres(id, name) VALUES ('15', 'Strategy');
INSERT INTO genres(id, name) VALUES ('16', 'Turn-based strategy (TBS)');
INSERT INTO genres(id, name) VALUES ('24', 'Tactical');
INSERT INTO genres(id, name) VALUES ('25', 'Hack and slash/Beat ''em up');
INSERT INTO genres(id, name) VALUES ('26', 'Quiz/Trivia');
INSERT INTO genres(id, name) VALUES ('30', 'Pinball');
INSERT INTO genres(id, name) VALUES ('31', 'Adventure');
INSERT INTO genres(id, name) VALUES ('32', 'Indie');
INSERT INTO genres(id, name) VALUES ('33', 'Arcade');
INSERT INTO genres(id, name) VALUES ('34', 'Visual Novel');
INSERT INTO genres(id, name) VALUES ('35', 'Card & Board Game');
INSERT INTO genres(id, name) VALUES ('36', 'MOBA');
